version: '3.9'
services:
  app:
    container_name: app_container
    environment:
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_DRIVER=${DB_DRIVER}
    tty: true
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - database
    networks:
      - application

  database:
    image: postgres:latest
    container_name: postgres_database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - app_data:/var/lib/postgresql/database
    networks:
      - application
      -
volumes:
  app_data:

# Networks to be created to facilitate communication between containers
networks:
  application:
    driver: bridge